// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM4quFixyMkKem2LBMc9mNbdgBeFqwqnU',
    appId: '1:109697453530:web:811a443dc7388dfdaac4e3',
    messagingSenderId: '109697453530',
    projectId: 'safepull-52920',
    authDomain: 'safepull-52920.firebaseapp.com',
    storageBucket: 'safepull-52920.firebasestorage.app',
    measurementId: 'G-JYJ3Q5RLQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYdcaDWuliE7LnsdaoPydK4czpL_7Jrug',
    appId: '1:109697453530:android:3d0edf7c8401e593aac4e3',
    messagingSenderId: '109697453530',
    projectId: 'safepull-52920',
    storageBucket: 'safepull-52920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjQPoDO4w_qcdxDCSfDpts32azPJN4tBE',
    appId: '1:109697453530:ios:de2e26f718493018aac4e3',
    messagingSenderId: '109697453530',
    projectId: 'safepull-52920',
    storageBucket: 'safepull-52920.firebasestorage.app',
    iosBundleId: 'com.example.safepull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjQPoDO4w_qcdxDCSfDpts32azPJN4tBE',
    appId: '1:109697453530:ios:de2e26f718493018aac4e3',
    messagingSenderId: '109697453530',
    projectId: 'safepull-52920',
    storageBucket: 'safepull-52920.firebasestorage.app',
    iosBundleId: 'com.example.safepull',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM4quFixyMkKem2LBMc9mNbdgBeFqwqnU',
    appId: '1:109697453530:web:3a90f7b4e802e8d5aac4e3',
    messagingSenderId: '109697453530',
    projectId: 'safepull-52920',
    authDomain: 'safepull-52920.firebaseapp.com',
    storageBucket: 'safepull-52920.firebasestorage.app',
    measurementId: 'G-5J8DB768GZ',
  );
}
